name: Bug Report
description: File a bug report to help us improve
title: "[Bug]: "
labels: ["bug", "triage"]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: dropdown
    id: platform
    attributes:
      label: Platform
      description: What platform are you running on?
      options:
        - Windows (PowerShell)
        - Linux (Bash)
        - macOS (Bash)
        - WSL (Windows Subsystem for Linux)
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Version Information
      description: |
        Provide version information for key components:
        - Docker version
        - Docker Compose version
        - PowerShell version (Windows)
        - Bash version (Linux/macOS)
      placeholder: |
        Docker: 24.0.6
        Docker Compose: 2.21.0
        PowerShell: 5.1.19041.3803
    validations:
      required: true

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to Reproduce
      description: Please provide detailed steps to reproduce the issue
      placeholder: |
        1. Run command '...'
        2. See error '...'
        3. Expected behavior was '...'
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant Log Output
      description: Please copy and paste any relevant log output
      render: shell

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our Code of Conduct
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
